name: tflite_object_detection
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.1.2
  image_picker: ^0.8.4+4
  cached_network_image: ^3.3.1


  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/model.tflite
    - assets/labels.txt

  uses-material-design: true

